# -*- coding: utf-8 -*-
"""etf1v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QUCUiQEItGC6kgZ5VB9zqy4dO0EjSapo
"""

import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta

"""### Read ETF Tickers

First, I'll define a function to read the ETF tickers from `etfslist.txt`. This function will handle cases where the file is not found or is empty, and it will clean up any trailing commas from the tickers.
"""

def get_etf_list(filename="etfslist.txt"):
    """Reads ETF tickers from a specified text file, one ticker per line, cleaning up formatting issues."""
    try:
        with open(filename, 'r') as f:
            etfs = [line.strip().replace(',', '') for line in f if line.strip()]
        if not etfs:
            print(f"Warning: The file '{filename}' was found but contains no ETF tickers.")
        return etfs
    except FileNotFoundError:
        print(f"Error: The file '{filename}' was not found. Please make sure it's in the correct directory.")
        print("Example etfslist.txt content:\nVTI\nVOO\nBND")
        return []

"""### Fetch Data and Calculate YTD Performance

Next, I will fetch the data using `yfinance` for all the ETFs for the current year to calculate their Year-to-Date (YTD) performance. I will then display these YTD returns.
"""

etf_tickers = get_etf_list()

if not etf_tickers:
    print("No ETF tickers found or file not accessible. Cannot proceed with YTD calculation or plotting.")
else:
    print(f"Found {len(etf_tickers)} ETFs: {', '.join(etf_tickers)}")
    today = datetime.now()
    # Calculate start of current year for YTD performance
    start_of_year = datetime(today.year, 1, 1)

    print(f"\n--- Calculating YTD Performance (from {start_of_year.strftime('%Y-%m-%d')} to {today.strftime('%Y-%m-%d')}) ---")
    try:
        # Fetch data for YTD
        ytd_data = yf.download(etf_tickers, start=start_of_year.strftime('%Y-%m-%d'), end=today.strftime('%Y-%m-%d'))

        if ytd_data.empty:
            print("No YTD data returned by yfinance. Skipping YTD calculation.")
        else:
            # Get the first and last close prices for YTD calculation
            first_prices = ytd_data['Close'].iloc[0]
            last_prices = ytd_data['Close'].iloc[-1]

            # Filter out any NaNs that might arise if an ETF didn't have data at start/end of year
            valid_first_prices = first_prices.dropna()
            valid_last_prices = last_prices.dropna()

            # Align indices to ensure we're comparing the same ETFs
            common_etfs = list(set(valid_first_prices.index) & set(valid_last_prices.index))
            if common_etfs:
                ytd_returns = ((valid_last_prices[common_etfs] - valid_first_prices[common_etfs]) / valid_first_prices[common_etfs]) * 100
                ytd_returns_df = pd.DataFrame(ytd_returns).rename(columns={0: 'YTD Return (%)'}).sort_values(by='YTD Return (%)', ascending=False)
                print("\nYear-to-Date (YTD) Performance:")
                display(ytd_returns_df)
            else:
                print("Could not calculate YTD returns for any ETF due to insufficient data.")
    except Exception as e:
        print(f"An error occurred while fetching YTD data: {e}")

"""### Plotting Historical Performance

Now, I will generate 5 plots side-by-side to visualize the historical performance of the ETFs over the requested timeframes: 6 months, 3 months, 1 month, 5 days, and 1 day.
"""

if etf_tickers:
    timeframes = {
        "6 Months": today - relativedelta(months=6),
        "3 Months": today - relativedelta(months=3),
        "1 Month": today - relativedelta(months=1),
        "5 Days": today - timedelta(days=5),
        "1 Day": today - timedelta(days=1)
    }

    print("\n--- Fetching all data for the longest timeframe (6 Months) ---")
    try:
        # Fetch all data once for the longest timeframe to optimize API calls
        all_etfs_data = yf.download(etf_tickers, start=timeframes["6 Months"].strftime('%Y-%m-%d'), end=today.strftime('%Y-%m-%d'))
        if all_etfs_data.empty:
            print("No data returned by yfinance for the 6 Months timeframe. Cannot plot any ETF.")
            all_etfs_data = None # Indicate no data was fetched
    except Exception as e:
        print(f"An error occurred while fetching all data: {e}")
        all_etfs_data = None

    if all_etfs_data is not None:
        # Iterate through each ETF and create a figure with 5 subplots for it
        for etf in etf_tickers:
            # Try to get 'Close' prices, handling cases where the ETF might not have data
            if ('Close', etf) in all_etfs_data.columns:
                etf_close_prices = all_etfs_data['Close'][etf].dropna()
            else:
                print(f"Warning: No 'Close' data found for {etf}. Skipping.")
                continue

            if etf_close_prices.empty:
                print(f"No valid closing price data available for {etf}. Skipping plot for this ETF.")
                continue

            fig, axes = plt.subplots(1, 5, figsize=(25, 5), sharey=False) # sharey=False to allow different y-scales for each subplot
            axes = axes.flatten() # Flatten the 2D array of axes for easier iteration

            fig.suptitle(f'ETF: {etf} - Historical Performance (Close Price)', fontsize=16, y=1.05) # Overall title for the ETF's figure

            for i, (title, start_date) in enumerate(timeframes.items()):
                ax = axes[i]

                # Filter data for the current timeframe
                current_etf_data = etf_close_prices[etf_close_prices.index >= start_date.strftime('%Y-%m-%d')]

                if current_etf_data.empty:
                    ax.set_title(f'{title} (No Data)')
                    ax.text(0.5, 0.5, 'No data', transform=ax.transAxes, ha='center', va='center', color='gray')
                    ax.set_visible(True) # Keep subplot visible to show 'No data'
                else:
                    current_etf_data.plot(ax=ax, linewidth=1.5, color='blue')
                    ax.set_title(f'{title}', fontsize=14)
                    ax.set_xlabel('Date', fontsize=10)
                    ax.set_ylabel('Price (USD)', fontsize=10)
                    ax.grid(True, linestyle='--', alpha=0.7)
                    ax.tick_params(axis='x', rotation=45)

            plt.tight_layout(rect=[0, 0.03, 1, 0.98]) # Adjust layout for suptitle
            plt.show()
            plt.close(fig) # Close the figure to free memory

        print("\n--- Data fetching and plotting process completed ---")
    else:
        print("Plotting skipped due to issues with fetching overall data.")
else:
    print("Plotting skipped because no ETF tickers were found.")